server_name: "&6&lNightmare&e&lPhoenix"
first_tempban: "4"      # in days only

database_host: ''
database_username: 'db_56351'
database_port: '3306'
database_password: ''
database_table_name_bans: 'BansPlugin'
database_table_name_join_quit: 'WebIntegrationJoinQuit'


# Permissions
# /ban -> Nightmare.ban
# /historial -> Nightmare.historial
# /unban -> Nightmare.unban
# /color -> nightmareutils.color