name: NightmareUtils
version: 1.1
author: Francisco Dadone
main: me.dadogamer13.nightmareutils.main.Main

commands:
  addban:
    aliases: [Ban added to db.]
    usage: /addban jugador razon
  historial:
    aliases: [historial de jugador]
    usage: /historial jugador
  removeban:
    aliases: [remover el ban]
  color:
    aliases: [cambia el color del nick]